name: Release All Sample Docker Images
run-name: ${{ inputs.release_type == 'Snapshot' && 'Publish Pre-release' || format('Release {0}', inputs.release_type)}} Docker Image by @${{ github.actor }}  
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'The type of release'
        options:
        - Major
        - Minor
        - Patch
        - Snapshot

jobs:
  incrementVersionNumber:
    uses: iabtechlab/uid2-shared-actions/.github/workflows/shared-increase-version-number.yaml@v3
    with:
      release_type: ${{ inputs.release_type }}
      working_dir: .
    secrets: inherit
    
  publishReverseProxyImage:
    uses: iabtechlab/uid2-shared-actions/.github/workflows/shared-publish-to-docker-versioned.yaml@v3
    needs: incrementVersionNumber
    with: 
      new_version: ${{ needs.incrementVersionNumber.outputs.new_version }}
      image_tag: ${{ needs.incrementVersionNumber.outputs.image_tag }}
      release_type: ${{ inputs.release_type }}
      docker_file: tools/reverse-proxy/Dockerfile
      docker_context: tools/reverse-proxy
      docker_image_name: iabtechlab/uid2-reverse-proxy
      docker_registry: ghcr.io
    secrets: inherit

  publishSecureSignalsClientServerImage:
    uses: iabtechlab/uid2-shared-actions/.github/workflows/shared-publish-to-docker-versioned.yaml@v3
    needs: incrementVersionNumber
    with: 
      new_version: ${{ needs.incrementVersionNumber.outputs.new_version }}
      image_tag: ${{ needs.incrementVersionNumber.outputs.image_tag }}
      release_type: ${{ inputs.release_type }}
      docker_file: web-integrations/google-secure-signals/client-server/Dockerfile
      docker_context: web-integrations/google-secure-signals/client-server
      docker_image_name: iabtechlab/uid2-google-secure-signals-client-server
      docker_registry: ghcr.io
    secrets: inherit

  publishSecureSignalsClientSideImage:
    uses: iabtechlab/uid2-shared-actions/.github/workflows/shared-publish-to-docker-versioned.yaml@v3
    needs: incrementVersionNumber
    with: 
      new_version: ${{ needs.incrementVersionNumber.outputs.new_version }}
      image_tag: ${{ needs.incrementVersionNumber.outputs.image_tag }}
      release_type: ${{ inputs.release_type }}
      docker_file: web-integrations/google-secure-signals/client-side/Dockerfile
      docker_context: web-integrations/google-secure-signals/client-side
      docker_image_name: iabtechlab/uid2-google-secure-signals-client-side
      docker_registry: ghcr.io
    secrets: inherit

  publishSecureSignalsServerSideImage:
    uses: iabtechlab/uid2-shared-actions/.github/workflows/shared-publish-to-docker-versioned.yaml@v3
    needs: incrementVersionNumber
    with: 
      new_version: ${{ needs.incrementVersionNumber.outputs.new_version }}
      image_tag: ${{ needs.incrementVersionNumber.outputs.image_tag }}
      release_type: ${{ inputs.release_type }}
      docker_file: web-integrations/google-secure-signals/server-side/Dockerfile
      docker_context: web-integrations/google-secure-signals/server-side
      docker_image_name: iabtechlab/uid2-google-secure-signals-server-side
      docker_registry: ghcr.io
    secrets: inherit

  publishSecureSignalsReactClientSideImage:
    uses: iabtechlab/uid2-shared-actions/.github/workflows/shared-publish-to-docker-versioned.yaml@v3
    needs: incrementVersionNumber
    with: 
      new_version: ${{ needs.incrementVersionNumber.outputs.new_version }}
      image_tag: ${{ needs.incrementVersionNumber.outputs.image_tag }}
      release_type: ${{ inputs.release_type }}
      docker_file: web-integrations/google-secure-signals/react-client-side/Dockerfile
      docker_context: web-integrations/google-secure-signals/react-client-side
      docker_image_name: iabtechlab/uid2-google-secure-signals-react-client-side
      docker_registry: ghcr.io
    secrets: inherit